# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.

# Qcom platform feature

#ifdef OPLUS_FEATURE_DUMP_DEVICE_INFO
obj-$(CONFIG_OPLUS_FEATURE_DUMP_DEVICE_INFO)	+=  qcom/dump_device_info/
#endif /* OPLUS_FEATURE_DUMP_DEVICE_INFO */

#ifdef OPLUS_FEATURE_DUMP_REASON
obj-$(CONFIG_OPLUS_FEATURE_DUMP_REASON)	+=  qcom/dump_reason/
#endif /* OPLUS_FEATURE_DUMP_REASON */

# MTK platform feature

# common feature
#ifdef OPLUS_FEATURE_THEIA
obj-$(CONFIG_OPLUS_FEATURE_THEIA) += common/theia/
#endif /* OPLUS_FEATURE_THEIA */

#ifdef OPLUS_FEATURE_LAST_BOOT_REASON
obj-$(CONFIG_OPLUS_FEATURE_LAST_BOOT_REASON) += common/last_boot_reason/
#endif /*OPLUS_FEATURE_LAST_BOOT_REASON*/

