obj-$(CONFIG_OPLUS_TRIKEY_HALL)	+= ist_hall_ic/
obj-$(CONFIG_OPLUS_TRIKEY_HALL)	+= hall_ic/
oplus_bsp_tri_key-y             += oplus_tri_key.o  tri_key_exception.o
oplus_bsp_tri_key-y             += tri_key_healthinfo.o tri_key_common_api.o
obj-$(CONFIG_OPLUS_TRIKEY_MAIN)      += oplus_bsp_tri_key.o
obj-$(CONFIG_OPLUS_TRIKEY_HALL)	+= digital_hall_ic/