# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2022 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_CMDLINE)     += cmdline_parser/
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX)     += oplus_phoenix/
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT)    += oplus_project/
ifdef CONFIG_OPLUS_SYSTEM_KERNEL_QCOM
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO) +=  project_info/
endif
